#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit -1
fi

OPTIND=1 # Reset getopts

# For future reference
# Run watch -n 0.1 'ls /dev | grep usbmodem; echo '-----------'; ls /dev'
# reset keyb make sure below matches

# Order:
# Run script flash 
# Reset keyboard
# Ensure it's in /dev/.., be fast it will dissapear 
# Press enter on the blocked flash script (use laptop keyboard as the other one is not working)

# SERIAL_PORT=/dev/ttyACM0
SERIAL_PORT=/dev/tty.usbmodem14201
LAYOUT=andrius
REFLASH_EEPROM=false
hands=()

# Parse arguments
args=$(getopt -o lr --long left,right,eeprom,layout: -n flash -- "$@")
if [[ $? -ne 0 ]] ; then
    exit -1
fi
eval set -- "$args"

# Load logic from arguments
while true ; do
    case "$1" in
    l|--left)  hands+=(left)  ; shift ;;
    r|--right) hands+=(right) ; shift ;;
    --eeprom) REFLASH_EEPROM=true ; shift ;;
    --layout) LAYOUT="$2" ; shift 2 ;;
    --) shift; break ;;
    *) break ;;
    esac
done

# If we weren't given any hand arguments, flash both
if [[ ${#hands[@]} -eq 0 ]] ; then
    hands=(left right)
fi

for hand in ${hands[@]} ; do
    read -r -p "Connect $hand hand, then reset" x
    if [[ "$REFLASH_EEPROM" == "true" ]] ; then
        sleep 2
        avrdude -p m32u4 -P $SERIAL_PORT -c avr109 -U "eeprom:w:quantum/split_common/eeprom-${hand}hand.eep" || exit 2
        sleep 1
        read -r -p "Reset again" x
    fi
    sleep 2
    avrdude -p m32u4 -P $SERIAL_PORT -c avr109 -U "flash:w:handwired_dactyl_manuform_4x6_${LAYOUT}.hex" || exit 3
done
